name: "test"

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: "Tests"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: 'true'

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-13

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.3
        with:
          version: "13"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: CMake start
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -B build

      -name: CMake build
        run: cmake --build build
